Add colouring of test failures

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -141,11 +141,7 @@ jobs:
       -
         name: Run tests
         run: |
-          go test -v ./internal/...
-          go test -v ./pkg/...
-          go test -timeout 20m -v ./test/tasks/... -always-keep-tmp-workspaces
-      -
-        name: Docker logs nexustest
-        if: ${{ failure() }}
-        run: |
-          docker logs nexustest
+          set -o pipefail
+          go test -v ./internal/... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
+          go test -v ./pkg/... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
+          go test -timeout 20m -v ./test/tasks/... -always-keep-tmp-workspaces | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
